"""add foreign key to Review

Revision ID: 2253b0aa4865
Revises: 63562aef541f
Create Date: 2024-11-28 16:45:05.127793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2253b0aa4865'
down_revision = '63562aef541f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_reviews_employee_id_employees'), 'reviews', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_employee_id_employees'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'employee_id')
    # ### end Alembic commands ###
